FROM ubuntu:14.04

RUN adduser --quiet --disabled-password qtuser

WORKDIR /usr/src/app

COPY CollisionProcess.py .
COPY CollisionWorker.py .
COPY GameServer.py .
COPY GameMode.py .
COPY GameWindow.py .
COPY LoadingScreen.py .
COPY ProcessEatFood.py .
COPY ProcessForce.py .
COPY ServerCommsWorker.py .
COPY Settings.py .
COPY Start.py .
COPY Worker.py .
COPY WorkerEatFood.py .
COPY WorkerForce.py .
COPY requirements.txt .

ADD Models /usr/src/app/Models
ADD resources /usr/src/app/resources

RUN apt-get update
RUN apt-get install -y python3
RUN apt-get install -y python3-pyqt5
